# Site
repository: riccardocogo93/riccardocogo93.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Riccardo Cogo
title: Ph.D. Student at University of Milano-Bicocca
email: r.cogo1@campus.unimib.it
# website: www.github.com/riccardocogo93/riccardocogo93.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  riccardocogo93
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: riccogo93
linkedin_username: riccardo-cogo-9039a6150
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. student in Statistics at the department of Economics, Management and Statistics (DEMS) of University of Milano-Bicocca ([ECOSTAT - XXXVI Cycle](https://www.dems.unimib.it/en/research/phd-programme)), and I am interested in Bayesian Nonparametrics. I currently live in Turin, Italy.

  I am also a Data Scientist at Intesa Sanpaolo and my job is the development of projects that, through machine learning algorithms and other quantitative methods, can lead to business development.

  Whether at work or University, I mainly use Python and R, but I am open to a variety of programming languages, which I used to cover the various phases of a data science project (data wrangling, modelling, programming and visualizing).

  My complete curriculum vitae is available at [this link](/files/CV_COGO.pdf).

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Milano-Bicocca
        sub_title: Ph.D. in Statistics
        # link: https://www.dems.unimib.it/en/research/phd-programme
        caption: 2020 - Present
        # quote: >
        description: | # this will include new lines to allow paragraphs
          Four year Ph.D. course, first 18 months are entirely dedicated to courses and exams

          Overall GPA (first year courses): 28.49/30

      - layout: left
        title: University of Turin
        sub_title: M.Sc. in Mathematics
        caption: 2015-2017
        # quote: >
        description: | # this will include new lines to allow paragraphs

          Overall GPA: 29.93/30. Final Mark: 110/110 with honors.

          <mark>Thesis Title</mark>: Study of Some Overdetermined Elliptic Problems (advisor: prof. [Paolo Caldiroli](https://www.matematica.unito.it/do/docenti.pl/Alias?paolo.caldiroli#tab-profilo)).

          In the context of elliptical problems with data on the edge, the thesis deals with overdetermined problems, i.e. those problems defined by a PDE defined on a domain and by two boundary conditions,
          a Dirichlet and a Neumann. The thesis considers some examples of overdetermined elliptic problems and assuming that they admit a solution,
          it makes an attempt to study the geometric and topological properties of its domain.

      - layout: left
        title: University of Turin
        sub_title: B.Sc. in Mathematics
        caption: 2012-2015
        # quote: >
        description: | # this will include new lines to allow paragraphs

          Overall GPA: 29.48/30. Final Mark: 110/110 with honors.

          <mark>Thesis Title</mark>: Area and Coarea Formulas and Their Applications in Integral Calculus (advisor: prof. [Paolo Caldiroli](https://www.matematica.unito.it/do/docenti.pl/Alias?paolo.caldiroli#tab-profilo)).

          This thesis deals with the complete demonstrations of the Area and Coarea Formulas and the presentation of some of their notable applications.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Big Data Lab @ Intesa Sanpaolo
        sub_title: Data Scientist
        caption: 2018 - Present
        # quote: >
        description: | # this will include new lines to allow paragraphs
            Part of the Data Science team, with the aim of developing end-to-end projects with other areas of the Bank. Projects are mostly developed as R or Python packages.

      - layout: left
        title: Sella Financial Markets @ Sella Holding
        sub_title: Junior Financial Analyst
        caption: 2017 - 2018
        # quote: >
        description: | # this will include new lines to allow paragraphs
            Developing of trading algorithms as well as analytical scripts to ensure the compliance of the trading strategies deployed with the European regulation Mifid II.

      - layout: left
        title: Sella Financial Markets @ Sella Holding
        sub_title: Financial Analyst Intern
        caption: 2017 (Fall)
        # quote: >
        description: | # this will include new lines to allow paragraphs
            Part of the team supporting the Senior VP of Market Division. Development of control algorithms for Market Abuse regulations.

      - layout: left
        title: University of Turin
        sub_title: Assistant and Tutor
        caption: 2016 - 2017
        # quote: >
        description: | # this will include new lines to allow paragraphs
            Tutor of the "Mathematical Analysis I" course (Department of Mathematics).

            Tutor of the "Maths and Physics" course (Department of Biological Sciences).

  - title: Courses and Summer Schools
    layout: text
    content: |
      Other courses I've followed.
      - **Big Dive: Data Science and Analytics**.Top-IX, Turin, Spring 2019 (Final Project: *NLP and NER on Corporate News*).

      Summer Schools.
      - **Advances in Artificial Intelligence**. University of Milano-Bicocca, Lake Como School of Advanced Studies, Como, 2019.
      - **Technical Analysis**. ASSIOM FOREX, Milan, 2018.
      - **Alpha Class**. University of Turin/Polytechnic of Turin, 2013.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
